document.go
document_test.go
emacs.go

FEATURE REQUEST
`_`: current cursor
You can not delete a word if there is a space before the cursor.
```console
>>> get pod _
```
When this change is patched,
```console
>>> get _
```
You can delete the word before cursor even if there is a space after word

Imitate general ControlW behavior

---

DEVELOPER_GUIDE.md

I was just wondering grammar mistakes and typos and fixed them as much as I can.
I believe someone will fix the wording and phrases correctly :)

Fix grammar mistakes and typos in DEVELOPER_GUIDE

---

render.go

In situations where a psuedo tty is allocated (e.g. within a docker container), window size via `TIOCGWINSZ` is not immediately available and will result in `0,0` dimensions, causing a divide by 0 error when `Render()` is called before the tty is fully setup.
However, in such circumstances, `SIGWINCH` is emitted when the psuedo tty allocation is complete. This change allows `go-prompt` to skip erase / height calculations when the initial window size is fetched (manually) as `0` and proceed as normal once the winch signal is received.

skip line erasing on render when window size is not yet available

---

windows_input.go

Current implementation doesn't read whole of key stroke. This change read input which is buffered.
See: https://qiita.com/c-bata/items/54eee079cfe3cda02eee

read buffered input

---

prompt.go

Hi, @c-bata !
I found some goroutine leaks in `prompt.go`.
the last goroutine which execute `p.readBuffer` will not be stoped when `C-d` entered because nobody doesn't notify to `stopReadBufCh`.

Fix goroutine leaks

---

CHANGELOG.md
_tools/complete_file/main.go
completer/file.go
completion.go
document.go
document_test.go
option.go
prompt.go
render.go

This PR fixed https://github.com/c-bata/go-prompt/issues/53
By using this feature, we can complete items which is not only separated by space. For example, we can complete files on your local machine like:
In https://github.com/c-bata/go-prompt/issues/66, Chyroc suggest that "," should have the same effect with ` `. I checked bash-shell's word separator by running `Ctrl + W` (Cut the word before the cursor) after input following text which includes `space`, `comma`, `period`, `colon`, `semi-colon` and `em space`.
```
$ abc def,hij.klm;opq　rsu:vwx
. <- cursor is here
```
then `Ctrl + W` removes until space. The result is below:
```
$ abc
.
```
From this behavior, I think we should only set `space` as a default word separator. This is the same as ever.
There is the scene to customize word …

Add option to customize insertion points for completions

---

CHANGELOG.md
document.go
key_bind_func.go
option.go
output.go
output_vt100.go

https://github.com/c-bata/go-prompt/pull/83 has a breaking api changes for users who customize ConsoleParser or ConsoleWriter. So I tagged v0.2.2 on current implementation on master branch.
I confirmed this release works fine on following terminal emulators.
* iTerm2(macOS)
* Command prompt (Windows 10)

Update CHANGELOG for v0.2.2 release.

---

input_posix.go

fixes https://github.com/c-bata/go-prompt/issues/88

use fresh /dev/tty fd for stdin in input parser

---

output_posix.go

Sometimes write system call returned "resource temporarily unavailable" in go-prompt. I don't know why but probably the reason might that terminal mode was changed in my unexpected trigger. Anyway, It will be fixed to retry syscall.Write.
related issue is https://github.com/c-bata/kube-prompt/issues/29

Modify flush in writer

---

filter.go
filter_test.go

This completion filter is similar to fuzzy-finder search tools, which match as long as all search characters are present and in order. I find it a very effective method for rapidly searching.
I also factored out some repeated code that would otherwise appear in four functions. If you don't like that I can undo that part.

Add fuzzy match filter

---

option.go
output_posix.go
output_windows.go

Add `NewStderrWriter` to support stderr output. To close https://github.com/c-bata/go-prompt/pull/101
Usage is like this:
```go
package main
import (
"fmt"
"github.com/c-bata/go-prompt"
)
func completer(in prompt.Document) []prompt.Suggest {
s := []prompt.Suggest{
{Text: "users", Description: "Store the username and age"},
{Text: "articles", Description: "Store the article text posted by user"},
{Text: "comments", Description: "Store the text commented to articles"},
{Text: "groups", Description: "Combine users with specific rules"},
}
return prompt.FilterHasPrefix(s, in.GetWordBeforeCursor(), true)
}
func main() {
in := prompt.Input(">>> ", completer,
prompt.OptionWriter(prompt.NewStderrWriter()))  // <- set stderr writer
fmt.Println("Your input: " + in)
}
```

Add NewStderrWriter

---

document_test.go

Characters in `Добрый день` are actually double-width on macOS terminals (confirmed on Terminal.app and iTerm2.app).
It caused test failure and I fixed it by modifying expected value. (I'm not sure updated *expected* value is actually what you expect, tho...)

Fix test on macOS

---

completion.go
option.go
prompt.go

I'm using this library for `Prompt.Call` to choose one from several candidates.
The pain point for me was no completion window is not shown at start. Users cannot notice that it supports completion until they input first character. However, in context where users choose one of candidates, they need to know what character should be input at first. However they can't since there is no candidate shown at start.
So I added one small option `OptionShowCompletionAtStart` to show completion just after starting selection, which is disabled by default. I could not add any test for this since there is no test for `prompt.Input` and `prompt.Option*`.
I've just started to use this library. So it may be possible to do that without adding a new option. In the case, I'll be happy if you kindly tell how …

Add option to show completion at start on Prompt.Input()

---

_example/http-prompt/main.go

Implement the exit function on the http-prompt example.

Fix http-prompt example (no exit)

---

go.mod
option.go
render.go
render_test.go

It's sometimes useful to run a function everytime there's a line break -- Enter as well as, for example, ControlC.
With this PR, a new option is added to assign a callback that gets
called every time `renderer.BreakLine()` is called.
Added a test that makes sure the renderer doesn't break if the callback is
not specified, as well as to check that it runs ok when the callback executes.
Just to give a bit more of context: in [ABS](https://github.com/abs-lang/abs)
we are trying to implement ControlR (reverse search), and need to clear
the search selection every time the user "clears" the console, either by
pressing enter or by clearing the current line (eg. ControlC).

Added OptionBreakLineCallback, to run a callback every time there's a line break

---

option.go
prompt.go

go-prompt, when used with OptionShowCompletionAtStart, display the list of possible completion.
The users will (almost always) try and access those options through the down arrow (instead of tab)
They take time realizing that:
- tab must be used first
- then up and down arrows work as expected.
With the new option OptionCompletionOnDown, the down arrow key will trigger access to the first completion (since there is no "newer" history to read from the buffer)
That is more intuitive for users: they can start with the down arrow immediately and select the right completion from the displayed list of completion (again, because of OptionShowCompletionAtStart)
Without OptionCompletionOnDown, go-prompt behaves as it does today: no changes.

Down Arrow for first completion

---

buffer.go
document.go
prompt.go

Hello, 
I am currently using go-prompt to build a cli tool, and I was wondering how to get the last key stroke in a Completer (using the Document).
Therefore, I created this PR which will attach the last key stroke to the buffer and update the document with each new feed.
The reason of doing this is to check for inputs (input.go) in each iteration of the completer. This for example enables users to exclude certain completions when pressing backspace. 
If there is a possibility to get the last key stroke in the current implementation, I would love to get some info.
Otherwise, I would be happy about any improvements to this PR.

Attach last key stroke to document

---

option.go
prompt.go

This allows go-prompt for loop in `Run()` to exit once a selection has been done.
Instead of just `os.Exit()` (which can be registered, but stops everything), you can add a simple exit function which will compare what has been selected in the prompt with a value.
If that matches, that exit functions returns true, go-prompt returns from `Run()`, and the rest of the Go program continues.
That allows to call go-prompt, select something, and then go on with the rest of the program.

ExitChecker: Exit go-prompt Run() for loop

---

prompt.go

#161  allows to exit go-prompt (not the all Go program like an `os.Exit()`, but just go-prompt) when the user type `<return>` and select an entry matching a criteria.
This PR adds the same exit-go-prompt option to each _key_ typed.
The general goal is to allow for an early exit as soon as a character (or sequence of characters) has been typed, without having to type `<enter>`.
Example use-case: a go-prompt with three choices 'yes', 'no', 'cancel'.
The following example would allow a user to select yes or no, just by typing 'y' or 'n' (no need to type `<return>`), or 'cancel' by typing ESC.
That would _not_ call `os.Exit`, just exit the go-prompt `Run()` loop, without executor.
````go
type choice struct {
isCancel bool
isYes    bool
}
func (c *choice) cancel(_ *prompt.Buffer) {
c.isCancel …
```

Trigger ExitChecker on pressed keys

---

render_test.go

`render_test.go` uses `PosixWriter`, which is defined in `output_posix.go`, a file marked with `+build !windows`
That means any test build would always fail on Windows, as shown in https://travis-ci.org/c-bata/go-prompt/builds/652864849, more precisely https://travis-ci.org/c-bata/go-prompt/jobs/652864854
.\render_test.go:74:9: undefined: PosixWriter
One solution (this PR) is simply to exclude `render_test.go` from build on Windows.
Another option might be to split it in two, if some part of that test file still warrant a build on Windows (while the part involving `PosixWriter` clearly does not)

Don't test render on Windows

---

buffer.go
completion.go
filter.go
output_vt100.go
output_windows.go
prompt.go
render.go
shortcut.go

The next series of PRs will aim to fix as many linter warnings as possible.
This one fixes:
golangci-lint.exe run --fast --exclude-use-default=false
This is the default linter integration with IDE like VSCode (https://github.com/golangci/golangci-lint#editor-integration)
Merging that PR means that, by default, the project compiles without warning.

Fix golangci-lint -fast warnings

---

internal/term/raw.go

When setting terminal mode, the character size is getting cleared and
defaults to CS5 which causes the display to be garbled.  Since the
purpose of this libaray is to mainly output readable characters, CS8 is
a better value.
This can be easily seen when launching go-prompt over serial connection.
Bug: #179
Change-Id: I4c9d13fad699e09aa9f4f665b252cebdd63614a7

termio: Set character width to 8 bits

---

go.mod
go.sum
internal/term/raw.go
internal/term/term.go

Updating `pkg/term` is necessary to fix #190 
For more background, latest version of `pkg/term` has a change in argument type of function `termios.Tcsetattr`. See https://github.com/pkg/term/pull/51 for more details.
Anyone using `go prompt` with explicit dependency of `pkg/term` to latest would encounter with issue #190

Update pkg/term module to latest and use unix.Termios
