emacs.go

I'm dying for this key bind.
It was easy to implement, but is there something wrong? Please let me know if I don't comply with your policies that define key bindings

Clear the screen like Ctrl-l behavior

---

prompt.go

Makes a copy of the bytes we read from stdin and sends those to the processing goroutine instead of a slice from our scratch buffer. This avoids sharing the same underlying array data across goroutines.
📎 #12

Fix data race in buffer read

---

completion.go
option.go
render.go

feat: implement pagination

---

_example/live-prefix/main.go
option.go
render.go

Hi!
I implemented live-prefix to solve #21 
In the process, I had found a new issue ( #27 ). This PR contains solution for this.
I'll be pleased if I can get your review :)
Thanks

Support updating the prefix dynamiacally

---

prompt.go

to support multiple platforms.

Change debug log filepath from env

---

render.go

fix: fix runtime error when r.col == 0

---

console_interface.go
posix_output.go
windows_output.go

Fix handling of question mark

---

README.md

Hi there!
Found this grepping our deps.
We've moved kubicorn to a new organization :)
Cheers!
Leigh

Update kubicorn link in README

---

README.md

This improves grammar and spelling in the README for smoother reading.

Improve grammar and spelling in README

---

Gopkg.lock
Gopkg.toml
_example/hello-cjk-cyrillic/main.go
buffer.go
buffer_test.go
completion.go
document.go
document_test.go
emacs_test.go
render.go

CJK and Cyrillic characters support.
Truncate with triple periods(`...`)
This PR fixes #75

Support CJK and Cyrillic characters

---

completion.go

Fix a truncate issue

---

output_vt100.go

To fix https://github.com/c-bata/go-prompt/issues/93. Original PR is https://github.com/c-bata/go-prompt/pull/85.

Fix resetting attributes

---

filter.go
filter_test.go

refs https://github.com/c-bata/go-prompt/pull/92

Add FilterFuzzy

---

.gitignore
.travis.yml
Makefile
README.md
output_posix.go

Add travis integration

---

Makefile
document.go
document_test.go
internal/bisect/bisect.go
internal/bisect/bisect_test.go
internal/strings/strings.go
internal/strings/strings_test.go

* Add an example
* Add benchmarks
* Fix bug of strings.IndexAny and strings.LastIndexAny.
* Add examples

Refactor a Document component

---

Makefile
completer/file.go
internal/strings/strings.go

golint is 97% at go report cards.
https://goreportcard.com/report/github.com/c-bata/go-prompt

Fix golint and improbe travis.yml

---

buffer.go
completion.go
emacs.go
input_posix.go
internal/debug/assert.go
internal/debug/log.go
output_posix.go
prompt.go
render.go
signal_posix.go
signal_windows.go

inspired by [apache arrow](https://github.com/apache/arrow/tree/master/go/arrow)

Add debug logger and assert

---

.travis.yml

Cache go mod files

---

input_posix.go

syscall.SYS_IOCTL is not available on some platforms (like Solaris).  Use unix.IoctlGetWinsize instead.

syscall.SYS_IOCTL is not portable

---

option.go

the option will modify the buffer content upon startup and works
in combination with `OptionShowCompletionAtStart()`.
somewhat related to #139

add support for managing the initial buffer content.

---

buffer.go

Remove empty if statements

---

.github/workflows/test.yml
README.md

See https://github.com/c-bata/go-prompt/pull/191#issuecomment-694971318

Replace CI status badge
